version: '3.6'

services:
  easy-certificate-creator:
    container_name: easy-certificate-creator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./openssl:/opt/openssl
      - ./entrypoint:/opt/entrypoint
    command: /bin/bash -c "chmod +x /opt/entrypoint/entrypoint.sh && /opt/entrypoint/entrypoint.sh"
